### ISSUE TITLE
Generating JavaScript bundles failed

### ISSUE THREAD

**Issue by tuanducdesign** [tuanducteam/tuanducdesign#11]
1:09:30 AM: failed Building production JavaScript and CSS bundles - 48.241s
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
1:09:30 AM: Error: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM:     at Processor.normalize (/opt/build/repo/node_modules/postcss/lib/processor.es6:139:15)
1:09:30 AM:     at new Processor (/opt/build/repo/node_modules/postcss/lib/processor.es6:38:25)
1:09:30 AM:     at postcss (/opt/build/repo/node_modules/postcss/lib/postcss.es6:34:10)
1:09:30 AM:     at /opt/build/repo/node_modules/postcss-loader/src/index.js:140:12
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: error Generating JavaScript bundles failed
1:09:30 AM: PostCSS plugin postcss-pxtorem requires PostCSS 8.
1:09:30 AM: Migration guide for end-users:
1:09:30 AM: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
1:09:30 AM: not finished Generating image thumbnails - 54.641s

**Comment by tuanducdesigner** [comment]
Fix done!
